from schema.te_ir import (
    AgentRole,
    AgentType,
    Archetype,
    AsymptoticClass,
    AsymptoticFamily,
    Bounds,
    BurnTriggerKind,
    CirculationSpeed,
    Condition,
    ContributionVerification,
    ControllingActor,
    CrossTokenAction,
    CrossTokenFlow,
    DistributionSpec,
    EmissionTriggerKind,
    EventOccurrence,
    FlowCoupling,
    FunctionShape,
    FunctionSign,
    GovernanceMaturity,
    GovernanceSpec,
    GovernanceType,
    HoldingIncentiveMechanism,
    HoldingTimeDistribution,
    InitialDistribution,
    InitialDistributionKind,
    Meta,
    NFRs,
    NumberRange,
    ParticipantsSpec,
    RedemptionMechanism,
    RegimeSwitch,
    Rule,
    RuleTrigger,
    SanctionKind,
    SanctionStructure,
    ScheduleModifiers,
    ThresholdCondition,
    ThresholdOp,
    ThresholdVar,
    TimeWindow,
    Token,
    TokenEarningMechanism,
    TokenEconomy,
    TokenFunction,
    Topology,
    ValueAnchor,
    VoteWeighting,
    load_te,
)

# Phase-A migration to v2: exposed under a sub-namespace so v1 imports
# (the entire __all__ below) are untouched. Consumers opt in explicitly:
#
#     from schema import v2
#     te = v2.load_te_v2("path/to/file.yaml")
#     te2 = v2.from_v1(v1_te)
#
# Live verifier / FM code continues to import v1 names from `schema`.
from schema import te_ir_v2 as v2  # noqa: F401

__all__ = [
    "AgentRole",
    "AgentType",
    "Archetype",
    "AsymptoticClass",
    "AsymptoticFamily",
    "Bounds",
    "BurnTriggerKind",
    "CirculationSpeed",
    "ContributionVerification",
    "ControllingActor",
    "Condition",
    "CrossTokenAction",
    "CrossTokenFlow",
    "DistributionSpec",
    "EmissionTriggerKind",
    "EventOccurrence",
    "FlowCoupling",
    "FunctionShape",
    "FunctionSign",
    "GovernanceMaturity",
    "GovernanceSpec",
    "GovernanceType",
    "HoldingIncentiveMechanism",
    "HoldingTimeDistribution",
    "InitialDistribution",
    "InitialDistributionKind",
    "Meta",
    "NFRs",
    "NumberRange",
    "ParticipantsSpec",
    "RedemptionMechanism",
    "RegimeSwitch",
    "Rule",
    "RuleTrigger",
    "SanctionKind",
    "SanctionStructure",
    "ScheduleModifiers",
    "ThresholdCondition",
    "ThresholdOp",
    "ThresholdVar",
    "TimeWindow",
    "Token",
    "TokenEarningMechanism",
    "TokenEconomy",
    "TokenFunction",
    "Topology",
    "ValueAnchor",
    "VoteWeighting",
    "load_te",
]
